README.md
[WEBRTC-454 - Repo url updated in podspec file](https://telnyx.atlassian.net/browse/WEBRTC-454)
---
Added all the steps required in order to configure TelnyxRTC from scratch to an Xcode project.
There were no steps on how to add TelnyxRTC from Cocoapods.
Steps added to configure the TelnyxRTC SDK into an Xcode project.
You will need to follow the README file project setup.
1. Check the new Section: Adding Telnyx SDK to your iOS Client Application. You can follow the steps and create a project from scratch.
=> WEBRTC-454 - Quickstart guide

TelnyxRTC.podspec
=> VIDEO-599 - Alpha release updated to v0.0.2

TelnyxRTC.podspec
SDK Version updated to v0.0.3 on podspec file
=> (WEBRTC-632) Alpha release updated to v0.0.3

TelnyxWebRTCDemo/Extensions/ViewControllerCallKitExtension.swift, TelnyxWebRTCDemo/ViewController.swift, TelnyxWebRTCDemo/Views/UISettingsView.swift, TelnyxWebRTCDemo/Views/UISettingsView.xib
[WebRTC-628 - Add Token login screen on Demo App](https://telnyx.atlassian.net/browse/WEBRTC-628)
---
A login switch selector has been added to the Settings screen. 
User can select to login using SIP credentials (user and password) or using a Telnyx token.
</br>
</br>
<table>
<tr>
<td>Login with Token</td>
<td>Login with SIP Credentials</td>
</tr>
<tr>
<td><img width="270" alt="Screen Shot 2021-07-13 at 13 33 29" src="https://user-images.githubusercontent.com/75636882/125490835-4b7da445-18e0-4c4c-bb24-a734b854b062.png"></td>
<td><img width="270" alt="Screen Shot 2021-07-13 at 13 33 09" src="https://user-images.githubusercontent.com/75636882/125490887-2f86675c-373a-43d8-b265-ba3019db0455.png"></td>
</tr>
</table>
Login with token was not supported on the demo app.
User can select between …
=> WEBRTC-628 - Add Token login screen on Demo App

README.md
[WEBRTC-731 - Update docs for Push Notifications / CallKit and PushKit implementation](https://telnyx.atlassian.net/browse/WEBRTC-731)
---
New documentation added for: 
- SIP Credentials
- Push notifications: portal setup
- Push notifications: app setup
- PushKit
- CallKit
=> (WEBRTC-731) Readme file updated.

TelnyxRTC.xcodeproj/project.pbxproj, TelnyxRTC/Telnyx/InternalConfig.swift, TelnyxRTCTests/Helpers/RTCTestDelegate.swift, TelnyxRTCTests/TelnyxRTCTests.swift, TelnyxRTCTests/WebRTC/CallTests.swift
- Removed the socket port number from the server url
=> chore: Removed port from server url

TelnyxRTC/Telnyx/Services/Socket.swift, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/Verto/Message.swift, TelnyxRTC/Telnyx/Verto/Method.swift, TelnyxRTCTests/Socket/SocketTests.swift
=> unit test for ping pong

.github/workflows/ios_fastlane_tests.yml, Podfile, TelnyxRTC.podspec, TelnyxRTC.xcodeproj/project.pbxproj, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxRTC/Telnyx/WebRTC/Peer.swift, TelnyxRTCTests/WebRTC/PeerConnectionTests.swift
Removed GoogleWebRTC and replace with WebRTC-lib
=> WebRTC Updated

Package.resolved, Package.swift
=> SPM implemented

README.md, TelnyxRTC/Telnyx/Services/Socket.swift
[TELAPPS-4593 ](https://telnyx.atlassian.net/browse/TELAPPS-4593)
---
Update Readme
=> Is/read me update/best practices

README.md
=> Update Read.me with Correct AnswerCall Method Name

Podfile, TelnyxRTC.xcodeproj/project.pbxproj, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/Utils/FileLoger.swift, TelnyxRTC/Telnyx/Utils/Logger.swift, TelnyxRTC/Telnyx/Verto/Message.swift, TelnyxRTC/Telnyx/Verto/StatsMessage.swift, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxRTC/Telnyx/WebRTC/Peer.swift, TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift, TelnyxWebRTCDemo/Extensions/ViewControllerVoIPExtension.swift, TelnyxWebRTCDemo/ViewController.swift
[WEBRTC-2220](https://telnyx.atlassian.net/browse/WEBRTC-2220)
[WEBRTC-2259](https://telnyx.atlassian.net/browse/WEBRTC-2259)
[WEBRTC-2220]: https://telnyx.atlassian.net/browse/WEBRTC-2220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEBRTC-2259]: https://telnyx.atlassian.net/browse/WEBRTC-2259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DebugStats Implementation & Auto Reconnect

TelnyxRTC/Telnyx/WebRTC/Peer.swift
[[WEBRTC-2352] [FIX] Prevent adding ICE candidates after negotiation ends or connection is established](https://telnyx.atlassian.net/browse/WEBRTC-2352)
---
- Added checks to prevent adding new ICE candidates if the negotiation has been marked as ended.
- Added a condition to skip adding ICE candidates when the connection state is already 'connected'.
- This prevents unnecessary candidate additions, ensuring stability in established connections.
[WEBRTC-2352]: https://telnyx.atlassian.net/browse/WEBRTC-2352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEBRTC-2352] [FIX] Prevent adding ICE candidates after negotiation ends or connection is established

CHANGELOG.md
[[WEBRTC-2342] [docs] CHANGELOG](https://telnyx.atlassian.net/browse/WEBRTC-2342)
---
- Changelog file added
[WEBRTC-2342]: https://telnyx.atlassian.net/browse/WEBRTC-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEBRTC-2342] [docs] CHANGELOG

docs-markdown/push-notification/app-setup.md, docs-markdown/push-notification/portal-setup.md
[WEBRTC-2384](https://telnyx.atlassian.net/browse/WEBRTC-2384)
---
Add Push Notification DOcs
[WEBRTC-2384]: https://telnyx.atlassian.net/browse/WEBRTC-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Push Notifications Docs

TelnyxRTC/Telnyx/Extensions/Dictionary+Extensions.swift, TelnyxRTC/Telnyx/Models/TxServerConfiguration.swift, TelnyxRTC/Telnyx/Verto/GatewayMessage.swift, TelnyxRTC/Telnyx/Verto/InfoMessage.swift, TelnyxRTC/Telnyx/Verto/Stats/DebugReportDataMessage.swift, TelnyxRTC/Telnyx/Verto/Stats/DebugReportStartMessage.swift, TelnyxRTC/Telnyx/Verto/Stats/DebugReportStopMessage.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCBundlePolicy+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCConfiguration+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCContinualGatheringPolicy+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCIceCandidate+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCIceConnectionState+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCIceGatheringState+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCIceServer+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCIceTransportPolicy+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCMediaStream+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCMediaStreamTrack+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCRtcpMuxPolicy+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCSdpSemantics+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTCSignalingState+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Extensions/RTClsCertPolicy+Extension.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCEventHandler.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsEvent.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsTag.swift
[[WEBRTC-2455] [fix] SPM build issue](https://telnyx.atlassian.net/browse/WEBRTC-XXX)
---
The import Foundation statement was added to the files that were missing the dependency.
=> [WEBRTC-2455] [fix] SPM build issue

TelnyxRTC.xcodeproj/project.pbxproj, TelnyxWebRTCDemo/AppDelegate.swift, TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController+VoIPExtension.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift, TelnyxWebRTCDemo/ViewModels/CallViewModel.swift, TelnyxWebRTCDemo/ViewModels/HomeViewModel.swift, TelnyxWebRTCDemo/ViewModels/ProfileViewModel.swift, TelnyxWebRTCDemo/Views/CallView.swift, TelnyxWebRTCDemo/Views/HomeView.swift, TelnyxWebRTCDemo/Views/ProfileView.swift, TelnyxWebRTCDemo/Views/SipCredentialsView.swift, TelnyxWebRTCDemo/Views/SipInputCredentialsView.swift, TelnyxWebRTCDemo/Views/SplashScreen.swift
[[WEBRTC-2423] [Feature] HomeScreen](https://telnyx.atlassian.net/browse/WEBRTC-2423)
---
- Migrated all views related to HomeView to use SwiftUI and the MVVM architecture.
- Replaced ViewController with HomeViewController.
- Replaced UICallView with CallView implemented in SwiftUI.
[WEBRTC-2423]: https://telnyx.atlassian.net/browse/WEBRTC-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEBRTC-2423] [Feature] Home View

TelnyxRTC/Telnyx/Models/TxServerConfiguration.swift, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController+VoIPExtension.swift, TelnyxWebRTCDemo/Views/CallView.swift
The SDK is not working properly when testing PN
=> Revert "[ENGDESK-38141] [fix] call states"

.idea/workspace.xml, TelnyxRTC/Telnyx/Models/TxServerConfiguration.swift, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController+VoIPExtension.swift, TelnyxWebRTCDemo/Views/CallView.swift
[ENGDESK-38141](https://telnyx.atlassian.net/browse/ENGDESK-38141)
---
Please provide a summary of the change / issue with a proper context.
- CallStates did not send a RECONNECTING event
- Call Recovery did not work when call is on foreground
- CallStates now send a RECONNECTING event
https://github.com/user-attachments/assets/fdb95cc9-d407-4b3c-80d7-c8d854b6033f
https://github.com/user-attachments/assets/101cb0fb-c890-4f86-80dc-0653a2af6453
[ENGDESK-38141]: https://telnyx.atlassian.net/browse/ENGDESK-38141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement Reconnecting CallState

TelnyxRTC.xcodeproj/project.pbxproj
[[WEBRTC-2508] [Feat]  Sample App renamed to Telnyx WebRTC](https://telnyx.atlassian.net/browse/WEBRTC-2508)
---
Updated the Sample App name to `Telnyx WebRTC`.
We removed the word `Demo` to prevent potential rejection from the App Store.
[WEBRTC-2508]: https://telnyx.atlassian.net/browse/WEBRTC-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEBRTC-2508] [Feat] Sample App renamed to Telnyx WebRTC

README.md
This PR adds a comprehensive table of contents to the README.md file with links to the documentation sections for Error Handling and Push Notifications.
- Added a Table of Contents section at the top of the README.md file
- Added links to the Error Handling documentation: `docs-markdown/error-handling/error-handling.md`
- Added links to the Push Notifications documentation:
- App Setup: `docs-markdown/push-notification/app-setup.md`
- Portal Setup: `docs-markdown/push-notification/portal-setup.md`
- Added a dedicated "Push Notifications Setup" section with links to the detailed documentation files
Resolves: [ENGDESK-39012](https://telnyx.atlassian.net/browse/ENGDESK-39012)
[ENGDESK-39012]: https://telnyx.atlassian.net/browse/ENGDESK-39012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> ENGDESK-39012: Add table of contents with links to error handling and push notifications documentation

docs-markdown/error-handling/error-handling.md
[ENGDESK-39012 Improve style of error handling title](https://telnyx.atlassian.net/browse/ENGDESK-39012)
---
removed h1 to improve styles when publishing these docs into developer-docs
=> [ENGDESK-39012] [docs] Improve style of error handling title

docs-markdown/push-notification/troubleshooting.md
This PR adds comprehensive troubleshooting documentation for iOS push notifications within the WebRTC SDK.
- Created troubleshooting.md in docs-markdown/push-notification directory
- Adapted Android troubleshooting guide for iOS-specific scenarios
- Added detailed sections for:
* VoIP Push Notification Certificate management
* APNS environment configuration
* Bundle ID and certificate matching
* Info.plist requirements
* Common issues and solutions
- Jira Ticket: [WEBRTC-2531](https://telnyx.atlassian.net/browse/WEBRTC-2531)
- Based on Android guide: [Android Troubleshooting](https://github.com/team-telnyx/telnyx-webrtc-android/blob/main/docs-markdown/push-notification/troubleshooting.md)
- Documentation review required
- Technical accuracy verification needed
- Links and references …
=> WEBRTC-2531: [IOS] Trouble Shooting Push Notification

README.md
This PR adds comprehensive documentation for the WebRTCStats onCallQualityChanged feature in the README.md file. The documentation includes:
1. How to use the onCallQualityChange callback
2. Details about the CallQualityMetrics properties
3. Information about the CallQuality enum values
4. Best practices for call quality monitoring
[WEBRTC-2662](https://telnyx.atlassian.net/browse/WEBRTC-2662)
[WEBRTC-2662]: https://telnyx.atlassian.net/browse/WEBRTC-2662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEBRTC-2662: Documentation for WebRTCStats onCallQualityChanged

TelnyxRTC/Telnyx/WebRTC/Call.swift
[ENGDESK-40725](https://telnyx.atlassian.net/browse/ENGDESK-40725)
---
- **SDK Release**: Follow all the steps listed on `Application Flow Checklist`.
- **Mobile App Release**: Run all the tests listed on `Application Flow Checklist`
- **Bugfixes or Demo App Changes**: Only include the tests relevant to the implemented changes.
1. Create a release branch for the demo app only.
2. Update the version.
3. Run all tests from `Application Flow Checklist`
4. Merge the PR.
5. Create a tag under release/sample-app/VERSION
6. Release app to the store.
1. Create a release branch by running the pipeline:
[Create Pull Request Pipeline](https://github.com/team-telnyx/telnyx-webrtc-ios/actions/workflows/release_01_create_pull_request.yml).
This will generate a branch named `release/RELEASE-X.X.X`.
2. …
=> Fix Ringback Tone for parked calls

.gitignore, README.md, docs-markdown/push-notification/troubleshooting.md, push-notification-tool/README.md, push-notification-tool/example-config.md, push-notification-tool/package-lock.json, push-notification-tool/package.json, push-notification-tool/src/index.ts, push-notification-tool/tsconfig.json
[WEBRTC-2916 - VoIP Push Notification Testing Tool](https://telnyx.atlassian.net/browse/WEBRTC-2916)
---
This PR adds a comprehensive VoIP push notification testing tool to help developers validate their iOS app integration with the Telnyx WebRTC SDK. The tool provides an easy way to send test VoIP push notifications directly to
devices using proper certificates and configuration.
- Developers had no built-in way to test VoIP push notifications
- Testing push notifications required complex setup with third-party tools
- Difficult to validate certificate configuration and payload structure
- No standardized way to troubleshoot push notification delivery issues
- Manual process to test different environments (sandbox/production)
- Developers can easily test VoIP push notifications using a …
=> [WEBRTC-2916] [Feature] VoIP Push Notification Testing Tool

QWEN.md, TelnyxRTC/Telnyx/Models/TxConfig.swift, TelnyxRTC/Telnyx/Services/Socket.swift, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/Utils/FileLoger.swift, TelnyxRTC/Telnyx/WebRTC/Call+IceRestart.swift, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxRTC/Telnyx/WebRTC/Peer+IceRestart.swift, TelnyxRTC/Telnyx/WebRTC/Peer.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift, TelnyxRTCTests/TelnyxRTCTests.swift, TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift, TelnyxWebRTCDemo/Extensions/UserDefaultExtension.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift, TelnyxWebRTCDemo/Views/CallView.swift, TelnyxWebRTCDemo/Views/HomeView.swift
[ENGDESK-44292 - Refersh Audio process](https://telnyx.atlassian.net/browse/ENGDESK-44292)
=> [fix] [ENGDESK-44292] Refresh Audio

Podfile, QWEN.md, TelnyxRTC.xcodeproj/project.pbxproj, TelnyxRTC/Telnyx/Models/TxConfig.swift, TelnyxRTC/Telnyx/Services/Socket.swift, TelnyxRTC/Telnyx/TxClient.swift, TelnyxRTC/Telnyx/Utils/FileLoger.swift, TelnyxRTC/Telnyx/Verto/ICERestartMessage.swift, TelnyxRTC/Telnyx/WebRTC/Call+IceRestart.swift, TelnyxRTC/Telnyx/WebRTC/Call.swift, TelnyxRTC/Telnyx/WebRTC/Peer+IceRestart.swift, TelnyxRTC/Telnyx/WebRTC/Peer.swift, TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift, TelnyxRTCTests/TelnyxRTCTests.swift, TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift, TelnyxWebRTCDemo/Extensions/UserDefaultExtension.swift, TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift, TelnyxWebRTCDemo/Views/CallView.swift, TelnyxWebRTCDemo/Views/HomeView.swift
[ENGDESK-44292 - Implement ICE Renegotiation and ACM Buffer Reset Based on RTT for Audio Delay Reduction](https://telnyx.atlassian.net/browse/ENGDESK-44292)
---
This PR implements advanced ICE candidate renegotiation and iOS AudioDeviceModule (ACM) buffer reset mechanisms based on real-time RTT monitoring to reduce audio delay during network quality fluctuations
without network changes.
- Audio delay accumulated during network quality degradation without automatic recovery
- No proactive ICE renegotiation based on RTT metrics
- iOS ACM buffers remained stretched after poor network conditions, causing persistent audio delay
- Manual intervention required to resolve audio quality issues during calls
- Limited automatic recovery mechanisms for network-induced audio problems
- **RTT-based …
=> [ENGDESK-44292] ICE Renegotiation and ACM Buffer Reset Based on RTT for Audio Delay Reduction
