TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/Models/TxCallInfo.swift
TelnyxRTC/Telnyx/Models/TxCallOptions.swift
TelnyxRTC/Telnyx/Verto/InfoMessage.swift
TelnyxRTC/Telnyx/Verto/Method.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTCTests/Verto/VertoMessagesTests.swift

[WebRTC-549 - Voice SDK DTMF implementation](https://telnyx.atlassian.net/browse/WEBRTC-549)
---
We are adding DTMF(Dual-tone multi-frequency signaling) support into the SDK.
- New Verto message is implemented: **telnyx_rtc.info**
- New function added to the Call class: `func dtmf(dtmf: String)`
- Added documentation markdown in code so the developer can access the examples of usage through the Quick Guide on Xcode:
<p align="center">
</p>
- Unit tests implemented to verify telnyx_rtc.info message encoding and decoding.
DTMF was not supported
DTMF is supported.
TODO: Add example on demo app.
1. Go to the demo app. 
2. Add a button into the UI.
3. Add the following code in the button press event: `self.currentCall?.dtmf("2")`
4. Run the app.
5. Call to **+13129457420**.
6. Bot will answer …

WEBRTC-549 - Voice SDK DTMF implementation

---

TelnyxRTC/Telnyx/Services/Socket.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxRTCTests/WebRTC/CallTests.swift
TelnyxWebRTCDemo/ViewController.swift
TelnyxWebRTCDemo/Views/UICallScreen.swift

[WebRTC-620 - Disconnect the client properly](https://telnyx.atlassian.net/browse/WEBRTC-620)
---
- The socket was not been disconnecting when calling` socket.disconnect()`. We are adding a call to force the socket disconnection: `socket.forceDisconnect()`.
- We are also hanging up all the ongoing calls (if there's any call connected), and cleaning the list of available calls.
- On the Demo App we are setting the Call Screen states in the correct status after disconnecting the client or when an ongoing call has ended. 
- The calls remain active and the socket remained connected after calling the `disconnect() `function.
- The client is disconnected properly when calling the `disconnect()` function and all the active calls are cancelled.
- The demo app updates the UI to the correct state …

WEBRTC-620 - Disconnect the client properly

---

TelnyxRTC/Telnyx/WebRTC/Call.swift

[WebRTC-615 - Stop ringback and ringtone](https://telnyx.atlassian.net/browse/WEBRTC-615)
---
We are stopping both ringtone and ringback tone whenever a WebRTC connection will be completed, that means that:
- A remote SDP has been received.
- Or we have answered the call.
Sometimes the ringtone or ringback tone kept playing once the call had been established.
Ringtone and ringback tone are stopped when a call is established. 
1. Go to the demo app. 
2. Connect using SIP credentials
3. Receive an incoming call
4. Accept the call
5. End the call.
6. Place an outbound call to a real phone number.
7. Reject the call from the remote phone.
8. Place an outbound call to a real phone number.
9. Answer the call
10. End the call.
For each scenario, both ringback and ringtone should be stopped.

WEBRTC-615 - Stop ringback and ringtone

---

TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/Verto/LoginMessage.swift

[WebRTC-643 - Fix: push_provider not been sent for credentials login](https://telnyx.atlassian.net/browse/WEBRTC-643)
---
In order to register a user to receive push notifications, the following parameters has to be sent inside the `login Verto `message as part of the `user variables`:
- push_notification_token
- push_notification_provider
**Example of login message:**
```
{
"id": "bcaa0286-4f54-440f-a0f9-e626d96878a4",
"params": {
"login": "sip_user",
"passwd": "sip_password",
"loginParams": {},
"userVariables": {
"push_device_token": "deviceToken",
"push_notification_provider": "ios"
}
},
"jsonrpc": "2.0",
"method": "login"
}
```
Push notifications parameters were not sent inside the user variable section of the login message
`push_device_token`  and `push_notification_provider` are …

WEBRTC-643 - Push notifications parameters Fix.

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Info.plist
TelnyxRTC/Telnyx/Verto/AnswerMessage.swift
TelnyxRTC/Telnyx/Verto/InviteMessage.swift
TelnyxRTC/Telnyx/Verto/Message.swift

[WebRTC-641 - Set User-Agent field with client type and version on INVITE ](https://telnyx.atlassian.net/browse/WEBRTC-641)
---
The `User-Agent` field is added inside the INVITE message to track outbound calls and inside the ANSWER message to track inbound calls.
This field contains ` PLATFORM-VERSION`
**Example of the new INVITE message:**
```
{
"jsonrpc": "2.0",
"method": "telnyx_rtc.invite",
"params": {
"User-Agent": "iOS-0.0.3", 
"sdp": "SDP",
"sessionId": "sessionID"
"dialogParams": {
"remote_caller_id_name": "",
"useStereo": false,
"screenShare": false,
"video": false,
"caller_id_name": "",
"caller_id_number": "",
"destination_number": "",
"callID": "callID",
"audio": true,
"attach": false
},
},
"id": "ID"
}
```
**Example of the new ANSWER message:**
```
{
"jsonrpc": "2.0", …
```

WEBRTC-641 - Set User-Agent field with client type and version on INVITE and ANSWER

---

TelnyxRTC/Telnyx/Services/Socket.swift
TelnyxRTC/Telnyx/Services/SocketDelegate.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/TxClientDelegate.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxWebRTCDemo/AppDelegate.swift
TelnyxWebRTCDemo/Views/UICallScreen.swift
TelnyxWebRTCDemo/Views/UIIncomingCallView.swift

[WEBRTC-648 - Fix memory leaks and retain cycles](https://telnyx.atlassian.net/browse/WEBRTC-648)
---
Make delegate references weak within the SDK and check for memory leaks.
All the delegate reference were declared strong that could result in strong reference cycles and memory leaks.
As a part of this PR, I have changed all the delegate to weak references to prevent strong reference cycles.
TODO: Resolve the memory leaks in WebRTC SDK.
- All the delegate references were strong.
- All the delegate references are weak.
1. Run the WebRTC demo app.
2. Login and make calls.
3. Check the memory graph post hanging up the call.
4. There should be no memory leak due to strong reference cycles within the TelnyxRTC SDK.
There are a few memory leaks in the WebRTC framework. Have opened a new …

WEBRTC-648 - Fix memory leaks and retain cycles

---

.github/pull_request_template.md

[WEBRTC-653 - GitHub - Create a default pull request template](https://telnyx.atlassian.net/browse/WEBRTC-653)
---
Added a default template for pull request.
- Contributors had to create the entire pull request body manually to describe the changes in the pull request.
- Now, all the project contributors will automatically see the template's contents in the pull request body for every new pull request they create.
- After merging this PR to `main`, going forward, all the new pull requests will be populated with the new template.

WEBRTC-653 - GitHub - Create a default pull request template

---

.github/workflows/ios_fastlane_tests.yml
TelnyxRTC.xcodeproj/xcshareddata/xcschemes/TelnyxRTCSDK.xcscheme
fastlane/Fastfile

[WEBRTC-649 - Improve GitHub action script that runs unit tests](https://telnyx.atlassian.net/browse/WEBRTC-649)
---
Improve GitHub action script that runs unit tests. Auto run the action on every PR. Generate on-demend credentials for token login.
- The github action that runs the unit tests was triggered manually.
- Token for login was not generated each time and tokens expire.
- After adding the pull request trigger, this action will now trigger on every PR
- Token is now generated when this action is triggered
1. Creating a pull request should trigger this action.

Webrtc 649 improve GitHub action script that runs unit tests

---

TelnyxRTCTests/Verto/VertoMessagesTests.swift
TelnyxRTCTests/WebRTC/CallTests.swift
TelnyxRTCTests/WebRTC/PeerConnectionTests.swift

[WEBRTC-655 - Fix unit tests](https://telnyx.atlassian.net/browse/WEBRTC-655)
---
Two test cases were fixed: 
- **Login Verto messages:** There was an issue related to the push notification variables. These variables has to be send inside the property "userVariables".
- **CallTests:** We were creating a socket object inside the setUpWithError function, now we move it as a property of the class CallTests. 
- Some unit tests were not working.
- Unit tests are working
1. Replace your SIP credentials and token on TestConstants.swift file.
2. Run` fastlane tests` 
3. Wait until all tests pass.

WEBRTC-655 - Fix unit tests

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/InternalConfig.swift
TelnyxRTC/Telnyx/Models/TxError.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/Verto/GatewayMessage.swift
TelnyxRTC/Telnyx/Verto/Method.swift
TelnyxWebRTCDemo/Extensions/UIViewControllerExtension.swift
TelnyxWebRTCDemo/ViewController.swift
TelnyxWebRTCDemo/Views/LoadingView.swift

[WEBRTC-646 - Handle Gateway states](https://telnyx.atlassian.net/browse/WEBRTC-646)
---
When the client logs in, the `telnyx_rtc.clientReady` message is received and it indicates that we have successfully logged in, but it not determines if the client can receive or place calls. 
In order to receive or make calls, the gateway must register the client after it logs in, and this process can take some time. If the user try to make a call as soon is logged in, but before the gateway registers it, the error `GATEWAY_DOWN` will be received.
Now on, after the `clientReady` is received, we start a process to request the gateway state and wait until its state is REGED (Registered). 
If the state is different than REGED, we retry requesting the state after 3 seconds, and this process is repeated …

WEBRTC-646 - Handle Gateway states

---

TelnyxRTC/Telnyx/Models/TxError.swift

[WEBRTC-660 - Fix pod lib lint warning](https://telnyx.atlassian.net/browse/WEBRTC-660)
---
There was a lint error that was producing a warning when running `pod lib lint`
- `pod lib lint` was failing
- `pod lib lint` is working

WEBRTC-660 - Fix pod lib lint warning

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/InternalConfig.swift
TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxRTC/Telnyx/Models/TxServerConfiguration.swift
TelnyxRTC/Telnyx/Services/Socket.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTCTests/Socket/SocketTests.swift
TelnyxRTCTests/WebRTC/CallTests.swift
TelnyxWebRTCDemo/Base.lproj/Main.storyboard
TelnyxWebRTCDemo/Extensions/UserDefaultExtension.swift
TelnyxWebRTCDemo/Extensions/ViewControllerCallKitExtension.swift
TelnyxWebRTCDemo/ViewController.swift

[WEBRTC-666 - Add hidden option to use dev TE](https://telnyx.atlassian.net/browse/WEBRTC-666)
---
- The `TxServerConfiguration` structure has been created to enable the developer to use their custom signaling server URL and custom TURN / STUN ICE servers when calling the `connect() `function of the TxClient.
- If the TxServerConfiguration is not specified when calling the `connect()` function, the default production Telnyx Servers will be used: Check `InternalConfig.swift` file.
- We can also pass the Telnyx environment thought the `TxServerConfiguration` (**production / development**). If no environment is specified, the production environment will be used as default.
- In the demo app a hidden menu has been implemented: To access to it, you must do a long press over the Telnyx logo. 
- …

WEBRTC-666 - Add hidden option to use dev TE

---

TelnyxRTC/Telnyx/Verto/LoginMessage.swift
TelnyxRTCTests/Verto/VertoMessagesTests.swift

[WEBRTC-661 - Send app push_notification_environment inside the Login message](https://telnyx.atlassian.net/browse/WEBRTC-661)
---
On this PR we are adding the `push_notification_environment ` field to send the app mode. If the app is in debug mode or production (app is signed). 
This is required to our PNS to determine if the PN has to be sent to **APNS sandbox** (app in debug mode) or **production** (app signed).
- App in `debug` mode: `push_notification_environment ="debug"`
- App `singed`: `push_notification_environment ="production"`
- No `push_notification_environment ` field was sent in the login message
- `push_notification_environment ` field send in the login message.
1. Run the app in debug mode.
2. Login using SIP credentials.
3. Check the logs and verify that we are sending …

WEBRTC-661 - Send app environment inside the Login message

---

.github/workflows/release_02_create_gh_release.yml
.github/workflows/release_03_deploy_cocoapods.yml
fastlane/Fastfile

[WEBRTC-715 - CI/CD Generate change-log and trigger Slack notification](https://telnyx.atlassian.net/browse/WEBRTC-715)
---
Release workflows updated:
- Change-log will be generated and added as a description when generating a new GitHub release.
- After a new SDK release is deployed to cocoapods a Slack notification will be triggered to an internal Slack channel.
- Change-log was not been generated.
- No Slack notifications.
- Change log is generated
- Slack notification is triggered when a new release is sent to Cocoapods.
Please mention pending items if any.

WEBRTC-715 - CI/CD Generate change-log and trigger Slack notification

---

TelnyxRTC/Telnyx/WebRTC/Call.swift

[WEBRTC-2104 - Call state is not updated to ACTIVE when remote answers the call](https://telnyx.atlassian.net/browse/WEBRTC-2104)
---
- When the call is answered by the remote participant, the call state was not transitioning to ACTIVE.
- Call state transitions to ACTIVE when the remote SDP is received (call was answered and connected)
1. Run the demo app in debug mode
2. Login with `User A` sip credentials or token on the app
3. Login with `User B` on the web dialer: [https://webrtc.telnyx.com/](https://webrtc.telnyx.com/)
4. Call `User B` from the app.
5. Answer the call from the web dialer.
Filter the logs on the app side with the following text `Call state updated` and you should see the following output:

fix: (WEBRTC-2104) Update call state to ACTIVE when remote answer the call

---

Package.resolved
Package.swift
README.md

[WEBRTC- Telapps 4386 ](https://telnyx.atlassian.net/browse/TELAPPS-4386)
---
Version Bump for SPM Package 
- StarScream **3.1.1 - 4.1.1**
- WebRTC **94.0.0 - 113.0.0**
Read Me Update for SPM
- StarScream Package was not on the same version as the Cocoapods Version
- SPM Works fine in Consuming Applications
Please mention pending items if any.
- TestTarget was causing build issues in client app. (Will fix this on later releases)
- Using Tags for SPM results in **Could not resolve url exception** (Not Fixed Yet) Client Apps would need to pull form main Branch when using SPM
1. Added TelnyxWebRTC using SPM to  https://github.com/team-telnyx/telnyx-webrtc-ios-examples.git. Works just as with cocoapods
CallKit Running using TelnyxWebRTC from SPM
<p align="center">
</p>

Telapps 4386 spm package fix

---

Podfile
TelnyxRTC.podspec
TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxWebRTCDemo/Extensions/AppDelegateTelnyxVoIPExtension.swift
TelnyxWebRTCDemo/ViewController.swift

[WEBRTC-IOS-SDK Ticket Call state going Active when call is ringing - Ifaxapp](https://telnyx.atlassian.net/browse/ENGDESK-22983)
---
Call state was being set to ```.Active```  when you receive the ```telnyx_media``` verto message. Added a new method to update SDP as well as set it to ```.Ringing``` State
- Call State is Active whilst Ringing for Offnet Calls.
- Call State is Active only when Active.
```pod lib lint``` has warnings. Check Issues
1. Added SPM and Cocoapods to client apps and tested

Is/bug fix/engdesk22983

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/TxClientDelegate.swift
TelnyxRTC/Telnyx/Verto/DisablePushMessage.swift
TelnyxRTC/Telnyx/Verto/Method.swift
TelnyxRTCTests/Helpers/RTCTestDelegate.swift
TelnyxRTCTests/TelnyxRTCMulticallTests.swift
TelnyxRTCTests/TelnyxRTCTests.swift
TelnyxWebRTCDemo/Extensions/AppDelegateTelnyxVoIPExtension.swift

[WEBRTC-4480 - Ticket title](https://telnyx.atlassian.net/jira/software/c/projects/TELAPPS/boards/98?modal=detail&selectedIssue=TELAPPS-4480&search=logout)
---
- onPushDisabled delegate added
- Classes Extending TxClientDelegate protocol must implement onPushDisabled(success, message)
New Feature Implementation
Refactor for backend to send success boolean
1.  Disable Push Notifications Works

Added Disable Push Notifications Functionality,

---

README.md
TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/Models/TxPushIPConfig.swift
TelnyxRTC/Telnyx/Models/TxServerConfiguration.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/Verto/AttachCallMessage.swift
TelnyxRTC/Telnyx/Verto/LoginMessage.swift
TelnyxRTC/Telnyx/Verto/Method.swift
TelnyxRTC/Telnyx/Verto/TxPushServerConfig.swift
TelnyxWebRTCDemo/AppDelegate.swift
TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift
TelnyxWebRTCDemo/Extensions/AppDelegateTelnyxVoIPExtension.swift

[WEBRTC-25284 - Ticket iOS SDK Answering from Push Notification Issue](https://telnyx.atlassian.net/browse/ENGDESK-25284)
---
- Added new method attachCalls
- The SDK now sends attachCalls rtc message when a PN is received
- Push Notifications now sends `rtc_ip` and `rtc_port` in meta data. This is used to setup `TxPushIPConfig` which directs rtc messages to the required instance the PN was initiated. 
- Update `0.1.8` will now require the `TxServerConfiguration(..)` param for `processVoIPNotification(..)` method
- PN Calls were not sending the INVITE message
- PN Calls work, and INVITE message is received
- Login param `attach_call` should later be removed and a version param sent instead
1. User Login - :white_check_mark:
2. Call is in Foreground - :white_check_mark:
3. Call is In …

Is/enhancement/attach calls - Release Candidate 0.1.8

---

TelnyxWebRTCDemo/Extensions/ViewControllerVoIPExtension.swift
TelnyxWebRTCDemo/ViewController.swift

[WEBRTC-26211 - Ticket title](https://telnyx.atlassian.net/browse/ENGDESK-26211)
---
Enabling Speaker Before Call is Active Works

Speaker Toggle Fix

---

TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTCTests/TelnyxRTCTests.swift
TelnyxRTCTests/WebRTC/CallTests.swift

[WEBRTC-24707 - Ticket title](https://telnyx.atlassian.net/browse/ENGDESK-24707)
---
Reconnect Socket and Login when connection is Lost
- Reconnection was not possible
- Socket will try to reconnect after connection is lost

Re-Establish Connection Feature

---

Podfile
TelnyxRTC.podspec
TelnyxRTC.xcodeproj/project.pbxproj

[TELAPPS-4753 -](https://telnyx.atlassian.net/browse/TELAPPS-4753)
---
Starscream crash fix for Xcode 15.0+
App crash due to Starscream
No App Crash

Fix Starscream Crash

---

TelnyxRTC.podspec
TelnyxRTC/Telnyx/TxClient.swift
TelnyxWebRTCDemo/Extensions/AppDelegateTelnyxVoIPExtension.swift

[ENGDESK-34578 - Ticket title](https://telnyx.atlassian.net/browse/ENGDESK-34578)
---
- Initialisead an early  call object to handle early Byes. 
- Handle `reportEnd` method for earlybye race conditions.
- Call continuos to ring for early byes 
Refactor Bye to happen without call object
1. Call/Pn WOrks

Fix Race Condition for Early Bye Message

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxWebRTCDemo/AppDelegate.swift
TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift
TelnyxWebRTCDemo/Extensions/UserDefaultExtension.swift
TelnyxWebRTCDemo/Extensions/ViewControllerVoIPExtension.swift
TelnyxWebRTCDemo/Extensions/WebRTCEnvironmentExtension.swift
TelnyxWebRTCDemo/Managers/SipCredentialsManager.swift
TelnyxWebRTCDemo/Models/SipUserCredential.swift
TelnyxWebRTCDemo/ViewController.swift
TelnyxWebRTCDemo/ViewControllers/SipCredentialsViewController.swift
TelnyxWebRTCDemo/ViewControllers/SipCredentialsViewController.xib
TelnyxWebRTCDemo/Views/UISettingsView.swift
TelnyxWebRTCDemo/Views/UISettingsView.xib
TelnyxWebRTCDemo/Views/UISipCredentialHeaderView.swift

[[WEBRTC-2351] [Feat] Support Multiple credentials in demo app](https://telnyx.atlassian.net/browse/WEBRTC-2351)
---
This PR introduces enhanced SIP credential management with support for handling multiple environments and improved user interaction for credential manipulation.
- SIP credentials are now stored based on the current environment (e.g., Development, Production). This ensures that credentials are isolated per environment, providing better organization and reducing potential mix-ups between different configurations.
- New credentials are added automatically after completing a successful connection sequence.
- The password for existing credentials is updated upon a successful connection process.
- Swipe to Delete SIP Credentials: Users can now easily delete SIP credentials using …

[WEBRTC-2351] [Feat] Support Multiple credentials in demo app

---

TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift
TelnyxWebRTCDemo/ViewController.swift
TelnyxWebRTCDemo/Views/UICallScreen.swift

[WEBRTC-2325 [FIX] Handle CallKit Mute / Unmute buttons](https://telnyx.atlassian.net/browse/WEBRTC-2325)
---
- Introduces a computed property isAudioTrackEnabled in the Peer class to check if the first audio track is enabled.
- Supports both PlanB and Unified Plan SDP configurations.
- Defaults to false if no audio track is available.
- Adds a new property isMuted to determine the mute state of a call.
- Implements provider(_:perform:) to handle mute/unmute actions through CallKit's CXSetMutedCallAction.
- Updates the Call class by integrating muteAudio() and unmuteAudio() methods to manage audio state.
- Ensures actions are fulfilled after processing for CallKit compliance.
Updates the Call mute/unmute state by:
- Accessing the call’s mute status.
- Propagating updates to CallKit by …

[WEBRTC-2325] [FIX] Handle CallKit Mute / Unmute buttons

---

TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift

[[ENGDESK-37644] [FIX] Fix CallKit speaker button inconsistency](https://telnyx.atlassian.net/browse/ENGDESK-37644)
---
Correct configuration of the `RTCAudioSession`
Evidence switching between Airpods, iPhone and SPeakers.
https://github.com/user-attachments/assets/cfd3c9c6-475b-447f-a5c7-46d499df55b5
[ENGDESK-37644]: https://telnyx.atlassian.net/browse/ENGDESK-37644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENGDESK-37644] [FIX] Fix CallKit speaker button inconsistency

---

TelnyxRTC.xcodeproj/project.pbxproj
TelnyxWebRTCDemo/ViewControllers/HomeViewController+VoIPExtension.swift
TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift
TelnyxWebRTCDemo/ViewModels/CallViewModel.swift
TelnyxWebRTCDemo/ViewModels/DTMFKeyboardViewModel.swift
TelnyxWebRTCDemo/ViewModels/HomeViewModel.swift
TelnyxWebRTCDemo/Views/CallView.swift
TelnyxWebRTCDemo/Views/DTMFKeyboardView.swift
TelnyxWebRTCDemo/Views/HomeView.swift

Implements a DTMF keyboard feature in the iOS Demo App as requested in WEBRTC-2465.
- Added DTMFKeyboardViewModel for handling DTMF functionality
- Created DTMFKeyboardView with a phone-like keypad layout
- Added DTMF button after speaker control in CallView
- Implemented bottom sheet presentation for the DTMF keyboard
- The DTMF button uses the `circle.grid.3x3.fill` SF Symbol icon
- Keyboard buttons use the specified colors:
- Background: #F5F3E4
- Foreground: #1D1D1D
- Bottom sheet presentation with fixed height of 400 points
- Text input field only accepts input from keypad buttons
https://github.com/user-attachments/assets/9f472638-6a90-4556-a97d-bc4e42b25e45
Jira Ticket: [WEBRTC-2465](https://telnyx.atlassian.net/browse/WEBRTC-2465)
[WEBRTC-2465]: …

[WEBRTC-2465][feat] Implement DTMF keyboard on Demo App

---

TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/TxClientDelegate.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift

This PR improves the documentation across several key components of the iOS SDK:
- Enhanced Call class documentation:
* Better examples and explanations
* Improved DTMF and mute functionality documentation
* Added comprehensive property descriptions
- Improved Peer class documentation:
* Detailed audio session handling explanation
* Better ICE negotiation documentation
* Added property descriptions
- Enhanced TxClientDelegate protocol documentation:
* Added usage examples
* Better method descriptions
* Improved event handling documentation
- Enhanced TxClient documentation:
* Improved audio session handling documentation
* Added audio route change monitoring details
* Better property descriptions
- Added detailed WebRTCStatsReporter documentation:
* Usage examples
* Event handling details …

WEBRTC-2470: Improve iOS SDK Documentation

---

README.md
TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/TxClientDelegate.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift

This PR improves the SDK documentation by:
1. Enhancing documentation wording and clarity:
- Improved SIP credentials constructor documentation
- Enhanced JWT token constructor documentation
- Fixed grammar and formatting in parameter descriptions
- Made documentation more consistent and professional
2. Adding comprehensive documentation for the `debug` variable:
- Added detailed documentation for the debug flag
- Clearly differentiated between `debug` and `logLevel` flags:
* `debug`: Enables sending WebRTC stats to Telnyx servers
* `logLevel`: Controls console logs in Xcode debug mode
- Noted that `debug` is disabled by default
- Added reference to `WebRTCStatsReporter` for more details
- Fixes WEBRTC-2470
- Documentation changes only, no functional changes
- Verified all documentation …

WEBRTC-2470: [IoS] Document Update

---

CHANGELOG.md
Package.resolved
Package.swift
Podfile
TelnyxRTC.podspec
TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/InternalConfig.swift
TelnyxRTC/Telnyx/TxClient.swift

[ENGDESK-38002 Remove Bugsnag dependency](https://telnyx.atlassian.net/browse/ENGDESK-38002)
---
Remove Bugsnag dependency
- We had a dependency with Bugsnag
- Bugsnag dependency removed
[ENGDESK-38002]: https://telnyx.atlassian.net/browse/ENGDESK-38002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENGDESK-38002] Remove Bugsnag dependency

---

Podfile
TelnyxRTC.podspec
TelnyxRTC.xcodeproj/project.pbxproj

[ENGDESK-38139 - Ticket title](https://telnyx.atlassian.net/browse/ENGDESK-38139)
---
- Updated StarScream dependency to 4.0.8. Based on this [issue](https://github.com/daltoniam/Starscream/issues/909), builds on M1 / M2 were fixed on version 4.0.5 
- Removed EXCLUDED_ARCHS configurations from podspec file

[ENGDESK-38139] Fix build on simulators

---

README.md
TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxRTC/Telnyx/TxClient.swift
TelnyxRTC/Telnyx/WebRTC/Call.swift
TelnyxRTC/Telnyx/WebRTC/Peer.swift
TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift
TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift
docs-markdown/structs/TxConfig.md

This PR introduces a new configuration option to control ICE transport policy, allowing developers to manage whether the SDK triggers the local network access permission request on iOS 15 and 17. By default, WebRTC gathers ICE candidates from the local network, which can prompt a permission request.
To align with the JS SDK, we are adding the `forceRelayCandidate` configuration, which enables developers to enforce TURN relay and avoid local network access.
- Implemented ICE transport policy control in Peer.swift.
- When forceRelayCandidate = true, the SDK:
- Forces `iceTransportPolicy = .relay`.
- Uses only TURN servers for media relay.
- Prevents the local network permission popup.
- By default, WebRTC's peer connection gathers ICE candidates from the local network, triggering a …

[ENGDESK-38176] [Feature] Add forceRelayCandidate to Force TURN Relay and Prevent Local Network Permission Request on iOS

---

TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxWebRTCDemo/Extensions/AppDelegateCallKitExtension.swift
TelnyxWebRTCDemo/Extensions/UserDefaultExtension.swift
TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift

[[WEBRTC-2505] [Feat] Handle JWT credentials](https://telnyx.atlassian.net/browse/WEBRTC-2505)
---
- User can login with JWT tokens and if it's valid it will be stored into the list of user credentials. 
- We are handling PN for JWT Tokens. When a PN is received it will connect to Telnyx using the JWT token. 
From the sample app:
1. Add a new JWT token
2. Login with JWT 
3. Kill the app
4. Place a call to the gencred associated with the JWT token. 
5. Answer the call
[WEBRTC-2505]: https://telnyx.atlassian.net/browse/WEBRTC-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEBRTC-2505] [Feat][Sample App] Handle JWT credentials

---

README.md
TelnyxRTC.xcodeproj/project.pbxproj
TelnyxRTC/Telnyx/Models/TxConfig.swift
TelnyxRTC/Telnyx/Utils/Logger.swift
TelnyxRTC/Telnyx/Utils/TxLogger.swift
TelnyxRTCTests/TelnyxRTCLoggerTests.swift

This PR implements a flexible logging solution that allows customers to override or extend the default Telnyx logging behavior. The goal is to empower developers to route SDK logs into their own logging frameworks or formats while still offering a simple default logger.
- Created  protocol for custom logging
- Added  as default implementation
- Updated  class to support custom loggers
- Added  parameter to 
- Added comprehensive documentation and examples in README.md
- Tested with default logger
- Tested with custom logger implementation
- Verified log level filtering works with custom loggers
- Verified thread safety with concurrent logging
- Added new section in README.md about custom logging
- Updated TxConfig documentation with new parameter
- Added example implementation and best …

[WEBRTC-2480] [Feature]: Add custom log implementation

---

docs-markdown/sample-app/ui-tests/README.md

This PR adds documentation on how to run UI Tests on Firebase Test Lab locally for the iOS WebRTC SDK.
- Created directory structure: docs-markdown/sample-app/ui-tests/
- Added README.md with comprehensive instructions on how to run UI Tests on Firebase Test Lab
- Improved formatting and organization of the documentation
- Added troubleshooting section and additional resources
[WEBRTC-2528](https://telnyx.atlassian.net/browse/WEBRTC-2528)
[WEBRTC-2528]: https://telnyx.atlassian.net/browse/WEBRTC-2528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEBRTC-2528: [iOS] Add docs on how to run UI Tests

---

TelnyxWebRTCDemo/Accessibility/AccessibilityIdentifiers.swift
TelnyxWebRTCDemo/Views/SipCredentialRow.swift
TelnyxWebRTCDemo/Views/SipCredentialsView.swift
TelnyxWebRTCDemo/Views/SipInputCredentialsView.swift

This PR improves the user experience in the TelnyxWebRTCDemo app by allowing users to edit existing credentials and optimizing the deletion flow.
- Added edit (pencil) icon alongside the delete icon in SipCredentialRow
- Implemented edit functionality to pre-fill SipInputCredentialsView with selected credential data
- Added proper handling of token switch when editing credentials
- Implemented username validation to prevent duplicates
- Improved deletion process with a toast notification showing "Hold down to delete"
- Added accessibility identifiers for UI testing
- Verified that users can edit existing credentials
- Confirmed that the toast notification appears when attempting to delete a credential
- Tested that long-pressing the delete button successfully removes the credential
- …

WEBRTC-2525: [iOS] [WebRTC Demo App] Implement Edit credential feature

---

CHANGELOG.md

This PR adds a changelog entry for version 1.2.1, which includes the fix to disable WebRTC stats during socket reconnection process. This change improves call reconnection speed.
- Added changelog entry for version 1.2.1 in the CHANGELOG.md file
- Followed the same format as previous versions
- Provided a minimal description of the change
[WEBRTC-2521](https://telnyx.atlassian.net/browse/WEBRTC-2521)
[WEBRTC-2521]: https://telnyx.atlassian.net/browse/WEBRTC-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEBRTC-2521: Add changelog entry for version 1.2.1

---

Podfile
README.md.update
TelnyxRTC.xcodeproj/project.pbxproj

This PR fixes an issue where the TelnyxWebRTCDemo app fails to build in Release mode due to duplicate framework outputs.
When building the demo app in Release mode (for TestFlight), the build fails with the following error:
```
Multiple commands produce "/Library/Developer/Xcode/DerivedData/TelnyxRTC-ckxseibvnggntdgyakxtihczzzta/Build/Intermediates.noindex/ArchiveIntermediates/TelnyxWebRTCDemo/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/TelnyxRTC.framework"
```
This happens because both the main project and CocoaPods are trying to build the TelnyxRTC framework.
- Removed TelnyxRTC from the TelnyxWebRTCDemo target in the Podfile to avoid conflicts.
- Updated the post_install script to ensure TelnyxRTC is properly built and installed as part of the app's build process.
- Set …

WEBRTC-2545: Fix build demo app [Release mode]

---

TelnyxWebRTCDemo/ViewControllers/HomeViewController+VoIPExtension.swift
TelnyxWebRTCDemo/ViewControllers/HomeViewController.swift
TelnyxWebRTCDemo/ViewModels/HomeViewModel.swift

This PR implements a timeout mechanism in the iOS sample app to prevent it from getting stuck when connecting to rtc.telnyx.com when there is no internet connection or the server is unresponsive.
- Added a connection timeout property to `HomeViewModel` (30 seconds)
- Added a timer property to `HomeViewController` to track the connection timeout
- Implemented timer start/stop methods and timeout handling
- Added timer management in the connection flow:
- Start timer when connection is initiated
- Stop timer when connection is successful (onClientReady)
- Stop timer when connection fails (onClientError)
- Stop timer when user manually disconnects
When a timeout occurs, the app will:
1. Stop the loading indicator
2. Disconnect the socket
3. Show an alert to the user …

[WEBRTC-2557] [Feature] [Sample App] Implement connection timeout logic in sample app

---

TelnyxWebRTCDemo/Views/ProfileView.swift

- Added a maxWidth constraint of 150 points to the profile name Text component in ProfileView.swift
- Maintained left alignment (.leading) for the username text
- Kept the existing lineLimit(1) to ensure text truncation with ellipsis
- The profile name text will never overlap or push the button out of view
- Long usernames will be truncated gracefully with an ellipsis
- The 'Switch Profile' button will always be fully visible and aligned to the right of the profile name
- Layout remains responsive and visually consistent across different device sizes
- Tested with various profile name lengths to ensure proper truncation and layout
- Verified that the 'Switch Profile' button remains visible at all times
[WEBRTC-2685](https://telnyx.atlassian.net/browse/WEBRTC-2685)
[WEBRTC-2685]: …

WEBRTC-2685: [iOS][Sample App] Fix Profile Name Overflow Affecting Switch Profile Button Layout

---

TelnyxRTC/Telnyx/WebRTC/Call.swift

[ENGDESK-42548](https://telnyx.atlassian.net/browse/ENGDESK-42548)
---
Background
There is a minor bug in the iOS SDK where the call termination cause code is incorrect regardless of the scenario.
Current Behavior
Rejecting an incoming call uses 
USER_BUSY
cause code ✓ (correct)
Ending an existing call uses 
USER_BUSY
cause code ✗ (incorrect)
Expected Behavior
Incoming call that is rejected  -> USER_BUSY  cause code
Existing call that is ended  -> NORMAL_CLEARING cause code
Ensured that on the SDK side, when ending a call, we are using the appropriate cause code (NORMAL_CLEARING).
[ENGDESK-42548]: https://telnyx.atlassian.net/browse/ENGDESK-42548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENGDESK-42548] [FIX] Termination cause codes

---

.github/workflows/ios_fastlane_tests.yml
.github/workflows/release-02-generate-docs.yml
.github/workflows/tests-ui-sample-app-firebase.yml

Ticket: WEBRTC-2921
Summary
- Update GitHub Actions to use Xcode 16.4.0 via maxim-lobanov/setup-xcode@v1.
- Updated workflows:
- ios_fastlane_tests.yml
- release-02-generate-docs.yml
- tests-ui-sample-app-firebase.yml
Rationale
- Xcode 15.4.0 is no longer available on GitHub macOS runners (error: Could not find Xcode version 15.4.0).
- 16.4.0 is available and stable on runners.
Validation notes
- Only CI configuration changed; no source code modifications.
- CI on this PR should pick up Xcode 16.4.0 and proceed.
Branch
- fix/WEBRTC-2921-github-actions
Testing
- Trigger ios_fastlane_tests and tests-ui-sample-app-firebase from the PR if not auto-triggered. Confirm Xcode 16.4.0 is selected and jobs succeed.

[WEBRTC-2921] - [iOS] Update actions to use Xcode 16
